{
 "title": "泰州学院",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "展示核心监控项(nacos monitor)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nacos配置服务个数(UP）",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(nacos_monitor{name=\"configCount\"})"
    }
   ]
  },
  {
   "title": "域名个数(service count）",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{name='domCount'})"
    }
   ]
  },
  {
   "title": "ip个数(ip count)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{name='ipCount'})"
    }
   ]
  },
  {
   "title": "配置个数(Nacos config)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{name='configCount', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "长连接数(Nacos config)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='longPolling'})"
    }
   ]
  },
  {
   "title": "读配置统计数(Nacos config)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='getConfig', instance=~'$instance'}) by (name)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "content": "<html>\n<body>\n<center>\n<a href=\"https://portal.tzu.edu.cn\">\n<img src=\"https://portal.tzu.edu.cn/static/img/logo.b597eb8d.png\" style=\"height: 50px;\" >\n</a>\n</center>\n</body>\n</html>"
  },
  {
   "title": "CPU使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(system_cpu_usage{instance=~'$instance'}) * 100"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", instance=~'$instance'})/sum(jvm_memory_max_bytes{area=\"heap\", instance=~'$instance'}) * 100"
    }
   ]
  },
  { "title": "警报列表", "type": "alertlist", "gridPos": { "h": 16, "w": 6, "x": 18, "y": 4 } },
  {
   "title": "threads(线程使用率)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jvm_threads_daemon_threads{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "http请求评价耗时",
   "type": "singlestat",
   "description": "http请求总耗时，包括多种(url,方法,code)\n除以\nhttp请求次数，包括多种(url,方法,code)",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "水平通知平均耗时",
   "type": "singlestat",
   "description": "Nacos config水平通知耗时\n除以\nNacos config水平通知次数",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(nacos_timer_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(nacos_timer_seconds_count{instance=~'$instance'}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "服务与服务平均推送耗时",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(nacos_monitor{name='avgPushCost', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "每秒平均http请求次数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m]))"
    }
   ]
  },
  {
   "title": "load",
   "type": "singlestat",
   "description": "需要结合cpu的核数来看，cpu核数=cpu数量*cpu核数\n如果 如上面所描述 cpu核数为1\nx<1 说明比较充裕\nx=1 说明需要注意了\nx>1 说明负载过高了",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(system_load_average_1m{instance=~'$instance'})"
    }
   ]
  },
  { "title": "展示指标的变化曲线 (nacos detail)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "耗时",
   "type": "graph",
   "description": "rt（http请求总耗时 除以 http请求次数）",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=~'/v1/cs/configs|/nacos/v1/ns', instance=~'$instance'}[1m])/rate(http_server_requests_seconds_count{uri=~'/v1/cs/configs|/nacos/v1/ns/instance|/nacos/v1/ns/health', instance=~'$instance'}[1m])) by (method,uri) * 1000",
     "legendFormat": "配置变更接口"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000",
     "legendFormat": "所有接口"
    }
   ]
  },
  {
   "title": "长连接数",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 21 },
   "repeat": "group",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='longPolling', instance=~'$instance'})",
     "legendFormat": "连接数"
    }
   ]
  },
  {
   "title": "负载每秒",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(system_load_average_1m{instance=~'$instance'})",
     "legendFormat": "负载"
    }
   ]
  },
  {
   "title": "每秒查询率（qps）",
   "type": "graph",
   "description": "qps",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=~'/v1/cs/configs|/nacos/v1/ns/instance|/nacos/v1/ns/health', instance=~'$instance'}[1m])) by (method,uri)",
     "legendFormat": "配置变更接口请求"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "所有请求"
    }
   ]
  },
  {
   "title": "角色状态",
   "type": "graph",
   "description": "leaderStatus",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='leaderStatus', instance=~'$instance'})",
     "legendFormat": "角色状态"
    }
   ]
  },
  {
   "title": "平均推送耗时",
   "type": "graph",
   "description": "avgPushCost",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='avgPushCost', instance=~'$instance'})",
     "legendFormat": "平均推送耗时"
    }
   ]
  },
  {
   "title": "最大推送耗时",
   "type": "graph",
   "description": "maxPushCost",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(nacos_monitor{name='maxPushCost', instance=~'$instance'})",
     "legendFormat": "最大推送耗时"
    }
   ]
  },
  {
   "title": "配置统计数",
   "type": "graph",
   "description": "config statistics",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='publish', instance=~'$instance'}) by (name)",
     "legendFormat": "写配置统计数"
    },
    {
     "expr": "sum(nacos_monitor{name='getConfig', instance=~'$instance'}) by (name)",
     "legendFormat": "读配置统计数"
    }
   ]
  },
  {
   "title": "健康检查次数",
   "type": "graph",
   "description": "health check",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_monitor{name=~'.*HealthCheck', instance=~'$instance'}[1m])) by (name) * 60",
     "legendFormat": "健康检查次数"
    }
   ]
  },
  { "title": "告警项(nacos alert)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CPU使用率",
   "type": "graph",
   "description": "cpu alert",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(system_cpu_usage) * 100", "legendFormat": "CPU使用率" }
   ]
  },
  {
   "title": "load 每秒(警告)",
   "type": "graph",
   "description": "load  alert",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "max(system_load_average_1m)", "legendFormat": "load" }
   ]
  },
  {
   "title": "内存警报",
   "type": "graph",
   "description": "memory alert",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})/sum(jvm_memory_max_bytes{area=\"heap\"}) * 100",
     "legendFormat": "内存警报"
    }
   ]
  },
  {
   "title": "线程数警告",
   "type": "graph",
   "description": "threads alert",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(jvm_threads_daemon_threads)",
     "legendFormat": "线程数"
    }
   ]
  },
  {
   "title": "gc警报",
   "type": "graph",
   "description": "gc alert",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(jvm_gc_pause_seconds_count{action=\"end of major GC\"}[5m])) * 300"
    }
   ]
  },
  {
   "title": "通知任务警报",
   "type": "graph",
   "description": "notify task alert",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='notifyTask'})",
     "legendFormat": "通知任务数量"
    }
   ]
  },
  {
   "title": "耗时警报",
   "type": "graph",
   "description": "rt alert",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[1m]))/sum(rate(http_server_requests_seconds_count[1m])) * 1000",
     "legendFormat": "耗时"
    }
   ]
  },
  {
   "title": "长轮询警报",
   "type": "graph",
   "description": "long polling alert",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(nacos_monitor{name='longPolling'})",
     "legendFormat": "长轮询"
    }
   ]
  },
  {
   "title": "配置不健康异常警报",
   "type": "graph",
   "description": "config unhealth exception alert",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='unhealth'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "数据库异常警报",
   "type": "graph",
   "description": "db exception alert",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='db'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "失败推送警报",
   "type": "graph",
   "description": "failed push alert",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='failedPush'})",
     "legendFormat": "失败"
    }
   ]
  },
  {
   "title": "请求参数不合法异常警报",
   "type": "graph",
   "description": "illegalArgument exception alert",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='illegalArgument'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "naming写磁盘异常",
   "type": "graph",
   "description": "naming disk exception alert",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='disk'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "配置通知异常警报",
   "type": "graph",
   "description": "config notify exception alert",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='configNotify'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "naming leader发送心跳异常",
   "type": "graph",
   "description": "naming leader send beat failed exception alert",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='leaderSendBeatFailed'}[1m])) * 60"
    }
   ]
  },
  {
   "title": "nacos异常警报",
   "type": "graph",
   "description": "nacos exception alert",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='nacos'}[1m])) * 60"
    }
   ]
  }
 ]
}